import { type NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";

// GET handler for fetching user's invite codes
export async function GET() {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);

  // Get the currently authenticated user
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "You are not authorized." }, { status: 401 });
  }

  try {
    // Fetch unused invite codes generated by this user
    const { data: inviteCodes, error } = await supabase
      .from("invite_codes")
      .select("*")
      .eq("generated_by_user_id", user.id)
      .eq("is_used", false)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching invite codes:", error);
      return NextResponse.json({ error: "Failed to fetch invite codes." }, { status: 500 });
    }

    return NextResponse.json(inviteCodes);
  } catch (error) {
    console.error("Server Error:", error);
    return NextResponse.json({ error: "An unexpected error occurred." }, { status: 500 });
  }
}
